language: php

dist: precise

sudo: false

php:
  - 5.5

before_script:
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml tests/
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
